application: gae-react-flux-todos
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /dist
  static_dir: dist
- url: /static
  static_dir: static
- url: /.*
  script: src.backend.routes.app

skip_files:
- ^(node_modules/.*)
